### ISSUE TITLE
增量同步失败

### ISSUE THREAD

**Issue by diqiuonline** [TraceNature/redissyncer-server#72]
2022-03-03 22:50:31.740|[WARN]|[FA657F2F4AAF4A718DCCAF349D9EEDF3: threadPoolTaskExecutor-4] -> CommandProcessingRdbMultiCommandSendStrategy#run:108 | taskId为[FA657F2F4AAF4A718DCCAF349D9EEDF3]的任务全量同步结束..进入增量同步模式 time:[0:s] 
2022-03-03 22:50:31.745|[INFO]|[FA657F2F4AAF4A718DCCAF349D9EEDF3: threadPoolTaskExecutor-4] -> DefaultSyncRedisProtocol#heartbeat:188 | [TASKID FA657F2F4AAF4A718DCCAF349D9EEDF3] heartbeat started.
2022-03-03 22:50:31.750|[INFO]|[FA657F2F4AAF4A718DCCAF349D9EEDF3: threadPoolTaskExecutor-4] -> JedisMultiExecPipeLineClient#commitCheckPoint:219 | commit first checkPoint
syncer.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hset' command
java.lang.NumberFormatException: For input string: "syncer.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hset' command"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at syncer.transmission.util.CommandCompensatorUtils.isLongOK(CommandCompensatorUtils.java:355)
	at syncer.transmission.util.CommandCompensatorUtils.isObjectSuccess(CommandCompensatorUtils.java:240)
	at syncer.transmission.util.CommandCompensatorUtils.isCommandSuccess(CommandCompensatorUtils.java:283)
	at syncer.transmission.client.impl.JedisMultiExecPipeLineClient.commitCompensator(JedisMultiExecPipeLineClient.java:1208)
	at syncer.transmission.client.impl.JedisMultiExecPipeLineClient.submitCommandNumNow(JedisMultiExecPipeLineClient.java:1173)
	at syncer.transmission.client.impl.JedisMultiExecPipeLineClient.commitCheckPoint(JedisMultiExecPipeLineClient.java:223)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingAofMultiCommandSendStrategy.run(CommandProcessingAofMultiCommandSendStrategy.java:66)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingDbMappingStrategy.toNext(CommandProcessingDbMappingStrategy.java:136)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingDbMappingStrategy.run(CommandProcessingDbMappingStrategy.java:127)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingDataAnalysisStrategy.toNext(CommandProcessingDataAnalysisStrategy.java:217)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingDataAnalysisStrategy.run(CommandProcessingDataAnalysisStrategy.java:202)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingSentinelCommandFileterStrategy.toNext(CommandProcessingSentinelCommandFileterStrategy.java:66)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingSentinelCommandFileterStrategy.run(CommandProcessingSentinelCommandFileterStrategy.java:56)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingCommandFilterStrategy.toNext(CommandProcessingCommandFilterStrategy.java:297)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingCommandFilterStrategy.run(CommandProcessingCommandFilterStrategy.java:74)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingTimeCalculationStrategy.toNext(CommandProcessingTimeCalculationStrategy.java:193)
	at syncer.transmission.strategy.commandprocessing.impl.CommandProcessingTimeCalculationStrategy.run(CommandProcessingTimeCalculationStrategy.java:184)
	at syncer.transmission.strategy.commandprocessing.ProcessingRunStrategyChain.run(ProcessingRunStrategyChain.java:57)
	at syncer.transmission.queue.SendCommandWithOutQueue.run(SendCommandWithOutQueue.java:77)
	at syncer.transmission.task.RedisDataSyncTransmissionTask$1.onEvent(RedisDataSyncTransmissionTask.java:223)
	at syncer.replica.listener.ValueDumpIterableEventListener.onEvent(ValueDumpIterableEventListener.java:63)
	at syncer.replica.listener.AbstractReplicationListener.doEventListener(AbstractReplicationListener.java:57)
	at syncer.replica.replication.AbstractReplication.submitEvent(AbstractReplication.java:147)
	at syncer.replica.replication.AbstractReplication.submitEvent(AbstractReplication.java:141)
	at syncer.replica.retry.SocketReplicationRetrier.open(SocketReplicationRetrier.java:192)
	at syncer.replica.retry.AbstractReplicationRetrier.retry(AbstractReplicationRetrier.java:42)
	at syncer.replica.retry.SocketReplicationRetrier.retry(SocketReplicationRetrier.java:275)
	at syncer.replica.replication.SocketReplication.open(SocketReplication.java:119)
	at syncer.replica.replication.RedisReplication.open(RedisReplication.java:256)
	at syncer.transmission.task.RedisDataSyncTransmissionTask.run(RedisDataSyncTransmissionTask.java:256)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-03-03 22:50:34.315|[ERROR]|[FA657F2F4AAF4A718DCCAF349D9EEDF3: threadPoolTaskExecutor-5] -> JedisMultiExecPipeLineClient#commitCompensator:1195 | pipeline返回size[0]:内存[20] 
syncer.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hset' command
Exception in thread "FA657F2F4AAF4A718DCCAF349D9EEDF3: threadPoolTaskExecutor-5" java.lang.NumberFormatException: For input string: "syncer.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'hset' command"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at syncer.transmission.util.CommandCompensatorUtils.isLongOK(CommandCompensatorUtils.java:355)
	at syncer.transmission.util.CommandCompensatorUtils.isObjectSuccess(CommandCompensatorUtils.java:240)
	at syncer.transmission.util.CommandCompensatorUtils.isCommandSuccess(CommandCompensatorUtils.java:283)
	at syncer.transmission.client.impl.JedisMultiExecPipeLineClient.commitCompensator(JedisMultiExecPipeLineClient.java:1208)
	at syncer.transmission.client.impl.JedisMultiExecPipeLineClient.submitCommandNum(JedisMultiExecPipeLineClient.java:1121)
	at syncer.transmission.client.impl.JedisMultiExecPipeLineClient$PipelineSubmitThread.run(JedisMultiExecPipeLineClient.java:1712)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

我修改了 syncer.transmission.util.redis.RedisUrlCheck.checkRedisUrl(String uri)方法 让他绝对放回true 还修改了syncer.replica.config.RedisURI#parse的方法 让特殊字符的密码可以传进去 要不然我没法解决密码中特殊字符的问题 不清楚是不是因为这个导致的

**Comment by diqiuonline** [comment]
我换成3.3.3版本可以增量同步了 但是还是不能让特殊字符的密码来创建任务
